version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - VITE_API_BASE=http://localhost:8000
    ports:
      - "5173:80"
    restart: unless-stopped

networks:
  default:
    name: eq_analytics_net
